<a href="https://colab.research.google.com/github/Aleks-cmyk/neural-netw/blob/master/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Task 2
NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця). Властивість shape та метод  reshape. Операції над масивами. Використати arange, random.

In [29]:
data = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]) # створення
add_data = np.array([])
 
print("Shape", data.shape) # розмірність

data_reshaped = np.reshape(data, (4, 3)) # змінити розмірність
print("Change shape (4, 3)")
display(data_reshaped)

add_data_v = np.array([5, 6, 7, 8])
newdata = np.vstack([data, add_data_v]) # додати рядок
print("Add row")
display(newdata)

newdata = np.append(data, [add_data_v], axis = 0) # додати рядок
print("Add row")
display(newdata)

add_data_h = np.array([[5], [6], [7]])
newdata = np.append(data, add_data_h, axis = 1) # додати стовпчик
print("Add col")
display(newdata)

data_arange = np.array(np.arange(10, 20, 0.5, dtype = float))  # створення масиву методом arange
data_arange = np.reshape(data_arange, (4, 5))
print("Using arrange")
display(data_arange)

data_rand = np.random.rand(4, 5) # створення масиву методом random
print("Using random")
display(data_rand)

Shape (3, 4)
Change shape (4, 3)


array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4]])

Add row


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

Add row


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

Add col


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 6],
       [1, 2, 3, 4, 7]])

Using arrange


array([[10. , 10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. , 14.5],
       [15. , 15.5, 16. , 16.5, 17. ],
       [17.5, 18. , 18.5, 19. , 19.5]])

Using random


array([[0.14423343, 0.25032326, 0.75986157, 0.5771226 , 0.88111271],
       [0.21006346, 0.15403265, 0.32021896, 0.32142739, 0.34613277],
       [0.84831991, 0.01824313, 0.90528575, 0.07147858, 0.62601333],
       [0.58854824, 0.20431274, 0.97123497, 0.15734591, 0.54437357]])

# Task 3
Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc, індексація з умовами відбору, групування, пошук «пустих» значень, сортування..);