<a href="https://colab.research.google.com/github/Aleks-cmyk/neural-netw/blob/master/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 2

студентки КН-31

Мензатюк Олександри

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

# Завдання 1


Створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [ ]:
tensor = tf.random.Generator.from_seed(42)
tensor = tensor.normal(shape=(3, 2))

print("Number of dimensions (rank):", tensor.ndim)
print("Shape of tensor:", tensor.shape)
print("Elements along axis 0 of tensor:", tensor.shape[0])
print("Elements along last axis of tensor:", tensor.shape[-1])
print("Total number of elements:", tf.size(tensor).numpy())

Number of dimensions (rank): 2
Shape of tensor: (3, 2)
Elements along axis 0 of tensor: 3
Elements along last axis of tensor: 2
Total number of elements (2*3*4*5): 6


Продемонструвати основні математичні операції над тензорами

In [ ]:
print(tensor)
print(tensor + 10)
print(tf.multiply(tensor, 10))
print(tf.matmul(tensor, tf.reshape(tensor, shape=(2, 3))))
print(tensor @ tf.transpose(tensor))
print(tf.tensordot(tensor, tf.reshape(tensor, shape=(2, 3)), axes=1))

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 9.24342   9.931453]
 [10.075951  8.742616]
 [ 9.768063  8.189215]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ -7.565803    -0.68547016]
 [  0.7595026  -12.573844  ]
 [ -2.3193765  -18.107855  ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.65860367 0.06775996 0.06666148]
 [1.5235531  0.28642863 2.2826219 ]
 [2.452333   0.43588796 3.2613285 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.57711244 0.02872748 0.2996034 ]
 [0.02872748 1.586784   2.2592378 ]
 [0.2996034  2.2592378  3.3327394 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.65860367 0.06775996 0.06666148]
 [1.5235531  0.28642863 2.2826219 ]
 [2.452333   0.43588796 3.2613285 ]], shape=(3, 3), dtype=float32)


Провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)


In [ ]:
print(tensor)
print(tf.reshape(tensor, shape=(1, 6)))
print(type(np.array(tensor)))
print(type(pd.DataFrame(tensor.numpy())))

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor([[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193765 -1.8107855 ]], shape=(1, 6), dtype=float32)
<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


## Завдання 2

1) Створять вектор, скаляр, матрицю і тензор з вибраними вами значеннями використовуючи tf.constant()

In [ ]:
scalar = tf.constant(7)
vector = tf.constant([10, 10])
matrix = tf.constant([[10, 7], [7, 10]])
tensor = tf.constant([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]],[[13, 14, 15],[16, 17, 18]]])

2) Знайдіть форму, ранг і розмір тензорів, які ви створили в попередньому завданні

In [ ]:
print("Scalar umber of dimensions (rank):", scalar.ndim)
print("Shape of scalar:", scalar.shape)
print("Scalar total number of elements:", tf.size(scalar).numpy())

print("Vector umber of dimensions (rank):", vector.ndim)
print("Shape of vector:", vector.shape)
print("Vector total number of elements:", tf.size(vector).numpy())

print("Matrix umber of dimensions (rank):", matrix.ndim)
print("Shape of matrix:", matrix.shape)
print("Matrix total number of elements:", tf.size(matrix).numpy())

print("Tensor umber of dimensions (rank):", tensor.ndim)
print("Shape of tensor:", tensor.shape)
print("Tensor total number of elements:", tf.size(tensor).numpy())

Scalar umber of dimensions (rank): 0
Shape of scalar: ()
Scalar total number of elements: 1
Vector umber of dimensions (rank): 1
Shape of vector: (2,)
Vector total number of elements: 2
Matrix umber of dimensions (rank): 2
Shape of matrix: (2, 2)
Matrix total number of elements: 4
Tensor umber of dimensions (rank): 3
Shape of tensor: (3, 2, 3)
Tensor total number of elements: 18


3) Створіть 2 тензора, що вміщюють випадкові значення між 0 і 1 з shape[5, 300]

In [ ]:
random_1 = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)

random_2 = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)

4) Помножте 2 тензора, що ви створили в 3, використовуючи матричне множення

In [ ]:
random_1 @ tf.transpose(random_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.058365, 73.9213  , 73.881035, 69.069534, 69.37678 ],
       [74.07802 , 72.15523 , 75.93146 , 68.62541 , 72.64904 ],
       [80.829735, 79.201706, 79.5987  , 74.35078 , 78.27825 ],
       [77.13292 , 72.54684 , 74.78005 , 70.28996 , 69.5191  ],
       [76.386955, 72.417465, 77.90748 , 71.03105 , 71.698135]],
      dtype=float32)>

5) Помножте 2 тензора, що ви створили в 3, використовуючи скалярне множення

In [ ]:
random_1 * random_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.02622198, 0.01961306, 0.19420348, ..., 0.516983  , 0.42356482,
        0.09731582],
       [0.8097447 , 0.26720786, 0.47073498, ..., 0.48357153, 0.3137142 ,
        0.0183854 ],
       [0.50091314, 0.34779754, 0.34451917, ..., 0.25047934, 0.01429857,
        0.12418132],
       [0.27377647, 0.6780451 , 0.14192013, ..., 0.119193  , 0.20820116,
        0.07484995],
       [0.45310932, 0.29225034, 0.7435735 , ..., 0.43292207, 0.0304953 ,
        0.02491996]], dtype=float32)>

6) Створіть тензор з випадковими значеннями між 0 і 1 за допомогою shape[224, 224, 3]

In [ ]:
random_3 = tf.random.uniform(shape=(224, 224, 3), minval=0, maxval=1)

7) Знайдіть мінімальне та максимальне значення тензору, який ви створили в 6

In [ ]:
print("maximum = ", tf.reduce_max(random_3).numpy())
print("minimum = ", tf.reduce_min(random_3).numpy())

maximum =  0.9999999
minimum =  1.0728836e-05


8) Створіть тензор з випадковим значенням shape[1,244,244,3], потім зжати його, щоб змінити форму на shape[244,244,3]

In [ ]:
random_4 = tf.random.uniform(shape=(1, 224, 224, 3))
print(tf.squeeze(random_4).shape)

(224, 224, 3)


9) Створіть тензор з формою [10] з випадковими значеннями, потім визначте індекс з найбільшим значенням

In [ ]:
random_5 = tf.random.uniform(shape=(10,), minval=0, maxval=10, dtype=tf.int32)
print(random_5)
print("Max value at index", tf.argmax(random_5).numpy())

tf.Tensor([6 0 3 8 0 0 3 4 8 9], shape=(10,), dtype=int32)
Max value at index 9


10) Гаряче кодування танзора з завдання 9

In [ ]:
print(tf.one_hot(random_5, depth=4))

tf.Tensor(
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(10, 4), dtype=float32)


# Висновок
В процесі виконання лабораторної роботи було ознайомлено з бубліотекою TensorFlow. Було засвоєно поняття тензору, вивчено і протестовано різні способи створення тензорів. Було створені надори данних різних розмірностей та проведено над ними різні математичні та CRUD операції. Також було вивчено як дізнатися розмір, розмірність та кількість вимірів тензору.